language: node_js
node_js:
  - '10'

# Skip building branches except for master for automated releases
branches:
  only:
    - master

# Cache dependencies
cache: npm

# Default install is npm install w/ package.json
# install

# Default script is npm test
# script

deploy:
  provider: script
  # Prevent Travis from resetting working directory after build
  skip_cleanup: true
  script: npx semantic-release
  on:
    branch: master
